### ISSUE TITLE
progress_displayers.py exception in 0.5.4

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#248]
I'm trying to test out the newest version of the engine (0.5.4) but every time I run a validation I'm getting the same error. I was previously using --disable-progressbar but with the new --progress flag I have tried running with --progress disabled, --progress verbose_output and even no --progress flag but each one returns the same error.

The full command I'm running is:
`core.exe validate -s sdtmig -v 3.4 -vo -of JSON -of XLSX -o <filename> -d <path>`

The error that's always returned is the following:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "scripts\run_validation.py", line 49, in validate_single_rule
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "core.py", line 428, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "core.py", line 199, in validate
  File "scripts\run_validation.py", line 110, in run_validation
  File "cdisc_rules_engine\utilities\progress_displayers.py", line 62, in _bar_progress_displayer
  File "multiprocessing\pool.py", line 870, in next
TypeError: 'NoneType' object is not subscriptable
[1216] Failed to execute script 'core' due to unhandled exception!
```

**Comment by nhaydel** [comment]
I am not able to reproduce this issue. Can you try without the -vo flag?

**Comment by jamesformedix** [comment]
Thanks for the prompt response Nic. Removed -vo and just went with --progress verbose_output and now it's working as expected. The README still has -vo listed so I didn't think to remove it.
