### ISSUE TITLE
CORE throws an unhandled error when one of the XPT files it's validating contains no observations

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#378]
We are getting an error when running a validation on a customer study, we think this is likely because there are no data records in one of the XPT files. We ran the validation individually on each XPT and the error was only thrown on the one file containing no observations. This causes a problem as it prevents the engine from generating a report for the validation of all the other valid datasets due to the error caused by the one empty XPT.

Below is the stack trace:
```
Traceback (most recent call last):

  File "core.py", line 433, in <module>

  File "click\core.py", line 1130, in __call__

  File "click\core.py", line 1055, in main

  File "click\core.py", line 1657, in invoke

  File "click\core.py", line 1404, in invoke

  File "click\core.py", line 760, in invoke

  File "click\decorators.py", line 26, in new_func

  File "core.py", line 199, in validate

  File "scripts\run_validation.py", line 98, in run_validation

  File "scripts\script_utils.py", line 92, in get_datasets

  File "cdisc_rules_engine\services\data_services\base_data_service.py", line 55, in inner

  File "cdisc_rules_engine\services\data_services\local_data_service.py", line 67, in get_dataset_metadata

  File "cdisc_rules_engine\services\data_services\local_data_service.py", line 194, in __get_dataset_metadata

  File "cdisc_rules_engine\services\data_services\local_data_service.py", line 179, in read_metadata

  File "cdisc_rules_engine\services\dataset_metadata_reader.py", line 32, in read

  File "cdisc_rules_engine\services\dataset_metadata_reader.py", line 60, in _extract_domain_name

  File "pandas\core\indexing.py", line 931, in __getitem__

  File "pandas\core\indexing.py", line 1566, in _getitem_axis

  File "pandas\core\indexing.py", line 1500, in _validate_integer

IndexError: single positional indexer is out-of-bounds

[24036] Failed to execute script 'core' due to unhandled exception!
```

**Comment by jamesformedix** [comment]
Looking at the function where the error is thrown from just now.
```
    def _extract_domain_name(self, df):
        first_row = df.iloc[0]
        if "DOMAIN" in first_row:
            domain_name = first_row["DOMAIN"]
            if isinstance(domain_name, bytes):
                return domain_name.decode("utf-8")
            else:
                return str(domain_name)
        return None
```
This should probably be a quick fix by just wrapping "first_row = df.iloc[0]" in a try - except IndexError block. Not sure what the best way of handling the IndexError should be though.

**Comment by nhaydel** [comment]
@jamesformedix That seems to be the issue. I think if an error is caught this function should just return None. Feel free to make a PR for the fix, otherwise we will get to this issue as our priority allows

**Comment by jamesformedix** [comment]
Getting "error: GH006: Protected branch update failed" when pushing the change locally and "Pre-receive hooks failed." when proposing the change in browser. Could one of the repo maintainer please give me write access so I can make the pull request. Thanks
